### ISSUE TITLE
It seems that the extension doesn't work well with files except .ts. 

### ISSUE THREAD

**Issue by Mingeax** [marinaglancy/vscode-bulk-problem-diagnostics#3]
When problems occur in TS files things are correct, but as for other types of files, .css for example, it just ignores those. Is it intentional?

**Comment by marinaglancy** [comment]
hi! I see you closed this issue, hope it works for you now. 
Just to comment here that the "Bulk problem diagnostics" extension does not actually raise any problems itself, it only helps to look for the problems raised by vscode core or other installed extensions. 

Vscode supports only a small number of languages out of the box, for other languages you need to install other extensions
